-- Create table for tracking user usage
create table if not exists public.user_usage (
  id bigint generated by default as identity primary key,
  ip_address text not null,
  user_email text,
  date date not null,
  count int default 0,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Add index for performance
create index if not exists idx_user_usage_ip_date on public.user_usage (ip_address, date);

-- Enable RLS (Optional, depending on your policy, keeping it open for service role)
alter table public.user_usage enable row level security;

-- Allow service role full access
create policy "Enable all access for service role" on public.user_usage
  as permissive for all
  to service_role
  using (true)
  with check (true);
