// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://imlbkhgquajmnqgbvgwj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImltbGJraGdxdWFqbW5xZ2J2Z3dqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM5MDA5NTAsImV4cCI6MjA2OTQ3Njk1MH0.J-baoXJnvpag7bEVSqbqXoAoGhAI7wnOb1osZcQo-Xk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});